services:
  distapp:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - docker-compose.env
  seaweedfs:
    image: chrislusf/seaweedfs:3.80
    command: server -dir="/data" -s3 -s3.port=8333 -volume.preStopSeconds=0 -s3.allowedOrigins="*" -master.raftHashicorp
    ports:
      - "8333:8333"
    volumes:
      - seaweedfs_data:/data
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - db:/var/lib/sqld
volumes:
  db:
  seaweedfs_data:
