name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile
    - run: bun run tests
  

    # E2E tests
    - name: Get installed Playwright version
      id: playwright-version
      run: |
        playwrightVersion=$(bunx playwright --version)
        echo "version=$playwrightVersion" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      id: playwright-cache
      with:
        path: '~/.cache/ms-playwright'
        key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: bunx playwright install --with-deps
    - name: Setup e2e env
      run: echo "${{ secrets.ENV_TESTS_BASE64 }}" | base64 --decode >> .env
    - run: bun run e2e
    - name: Deploy
      run: curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/344ca361-b2d3-48e6-b896-ffa2dd1e9a1b
