name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"

    - name: Install dependencies
      run: bun install --frozen-lockfile
    - run: bun run tests
  

    # E2E tests
    - name: Install seaweedfs
      run: |
        tools_folder="${{ github.workspace }}/bin_tools"
        mkdir -p "$tools_folder"
        curl -L -o seaweedfs.tar.gz https://github.com/seaweedfs/seaweedfs/releases/download/3.80/linux_amd64.tar.gz
        tar -xzf seaweedfs.tar.gz -C "$tools_folder"
        echo "$tools_folder" >> "$GITHUB_PATH"
    - run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/tursodatabase/libsql/releases/download/libsql-server-v0.24.28/libsql-server-installer.sh | sh
    - name: Get installed Playwright version
      id: playwright-version
      run: |
        playwrightVersion=$(bunx playwright --version)
        echo "version=$playwrightVersion" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      id: playwright-cache
      with:
        path: '~/.cache/ms-playwright'
        key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: bunx playwright install --with-deps
    - run: bun run e2e

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/344ca361-b2d3-48e6-b896-ffa2dd1e9a1b
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results
